## Import libraries

In [ ]:
import psycopg2
import pandas as pd
import os
import sys
sys.path.insert(0, os.path.abspath('..'))
from scripts.query_runner import run_query
from dotenv import load_dotenv

## Load .env file

In [ ]:
load_dotenv()

True

## Database Configuration

In [19]:
DB_CONFIG = {
    "host":     os.getenv("DB_HOST"),
    "database": os.getenv("DATABASE"),
    "user":     os.getenv("DB_USER"),
    "password": os.getenv("DB_PASSWORD")
}

## Connect to Postgres

In [20]:
conn = psycopg2.connect(**DB_CONFIG)

## Run Queries to Verify the Data

In [6]:
sql = "SELECT * FROM reviews;"

run_query(sql, conn)

c:\Users\hp\fintech-review-analytics\scripts\query_runner.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

,review_id,bank_id,review_text,rating,review_date,sentiment_label,sentiment_score,identified_theme,source
0,1,1,good,5,2026-05-12,POSITIVE,0.999816,General Satisfaction,Google Play
1,2,1,cbe,1,2026-05-12,POSITIVE,0.996601,Other,Google Play
2,3,1,good use,5,2026-05-12,POSITIVE,0.999846,General Satisfaction,Google Play
3,4,1,cbe,4,2026-05-11,POSITIVE,0.996601,Other,Google Play
4,5,1,best secured,5,2026-05-11,POSITIVE,0.999819,General Satisfaction,Google Play
...,...,...,...,...,...,...,...,...,...
1387,1388,3,user friendly using lite app fast easy remove ...,5,2022-07-18,NEGATIVE,-0.999198,Transaction Performance,Google Play
1388,1389,3,nice attractive application developed wonderful,5,2022-07-18,POSITIVE,0.999883,General Satisfaction,Google Play
1389,1390,3,amole lite simple kind payment thank dashen bank,5,2022-07-18,POSITIVE,0.998042,UI & User Experience,Google Play
1390,1391,3,app,4,2022-07-18,NEGATIVE,-0.840030,Other,Google Play
1391,1392,3,waiting long time amazing app thanks dashen ba...,5,2022-07-16,POSITIVE,0.999832,Transaction Performance,Google Play

## Count reviews per bank

In [8]:
sql = """
SELECT r.bank_name, COUNT(*) AS total_reviews
FROM reviews v
JOIN banks r ON r.bank_id = v.bank_id
GROUP BY r.bank_name;
"""

run_query(sql, conn)

c:\Users\hp\fintech-review-analytics\scripts\query_runner.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

                     bank_name  total_reviews
0                  Dashen Bank            468
1            Bank of Abyssinia            467
2  Commercial Bank of Ethiopia            457

## Average rating per bank

In [9]:
sql = """
SELECT r.bank_name, ROUND(AVG(v.rating), 2) AS avg_rating
FROM reviews v
JOIN banks r ON r.bank_id = v.bank_id
GROUP BY r.bank_name;
"""

run_query(sql, conn)

c:\Users\hp\fintech-review-analytics\scripts\query_runner.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

                     bank_name  avg_rating
0                  Dashen Bank        4.10
1            Bank of Abyssinia        3.55
2  Commercial Bank of Ethiopia        4.08

## Check for nulls

In [10]:
sql = """
SELECT *
FROM reviews
WHERE
    review_text IS NULL
    OR rating IS NULL
    OR review_date IS NULL
    OR sentiment_label IS NULL
    OR sentiment_score IS NULL
    OR identified_theme IS NULL
    OR bank_id IS NULL;
"""

run_query(sql, conn)

c:\Users\hp\fintech-review-analytics\scripts\query_runner.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(sql, conn)

Empty DataFrame
Columns: [review_id, bank_id, review_text, rating, review_date, sentiment_label, sentiment_score, identified_theme, source]
Index: []

> No null values in any of the columns and average rating, total review per bank and total rows consistent with CSV.